USE master;
GO

IF (EXISTS (SELECT name FROM master.sys.databases WHERE name = 'OLTP_GEEKMARKET'))
BEGIN
    DROP DATABASE OLTP_GEEKMARKET;
END;
GO

CREATE DATABASE OLTP_GEEKMARKET;
GO

USE OLTP_GEEKMARKET;
GO

-- Tablas principales de la base de datos
CREATE TABLE FECHAS (
    PERIODO NVARCHAR(8) PRIMARY KEY,
    FECHA DATE NOT NULL,
    ANHO INT NOT NULL,
    MES INT NOT NULL,
    DIA INT NOT NULL,
    NOMBRE_MES NVARCHAR(20) NOT NULL,
    MES_CORTO NVARCHAR(10) NOT NULL,
    TRIMESTRE NVARCHAR(10) NOT NULL,
    NOMBRE_DIA NVARCHAR(20) NOT NULL
);

CREATE TABLE PAISES (
    COUNTRY_ID INT PRIMARY KEY,
    COUNTRY_NAME NVARCHAR(255) NOT NULL,
    CITY_NAME NVARCHAR(255) NOT NULL
);

CREATE TABLE USUARIOS (
    USER_ID INT PRIMARY KEY,
    EMAIL NVARCHAR(255) NOT NULL,
    USER_TYPE NVARCHAR(10) NOT NULL,
    COUNTRY_ID INT FOREIGN KEY REFERENCES PAISES(COUNTRY_ID),
    CREATED_AT NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO)
);

CREATE TABLE PERSONAS_NATURALES (
    USER_ID INT PRIMARY KEY FOREIGN KEY REFERENCES USUARIOS(USER_ID),
    FIRST_NAME NVARCHAR(255) NOT NULL,
    LAST_NAME NVARCHAR(255) NOT NULL
);

CREATE TABLE EMPRESAS (
    USER_ID INT PRIMARY KEY FOREIGN KEY REFERENCES USUARIOS(USER_ID),
    RUC NVARCHAR(20) NOT NULL,
    BUSINESS_NAME NVARCHAR(255) NOT NULL
);

CREATE TABLE ALMACENES (
    WAREHOUSE_ID INT PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL,
    COUNTRY_ID INT FOREIGN KEY REFERENCES PAISES(COUNTRY_ID)
);

CREATE TABLE MARCAS (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL
);

CREATE TABLE CATEGORIAS (
    CATEGORY_ID INT PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL,
    DESCRIPTION NVARCHAR(255) NOT NULL
);

CREATE TABLE METODOS_PAGO (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255)
);

CREATE TABLE PRODUCTOS (
    PRODUCT_ID NVARCHAR(20) PRIMARY KEY,
    CATEGORY_ID INT FOREIGN KEY REFERENCES CATEGORIAS(CATEGORY_ID),
    BRAND_ID INT FOREIGN KEY REFERENCES MARCAS(ID),
    NAME NVARCHAR(255) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CREATED_AT NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO)
);

CREATE TABLE INVENTARIO (
    INVENTORY_ID INT PRIMARY KEY IDENTITY,
    PRODUCT_ID NVARCHAR(20) FOREIGN KEY REFERENCES PRODUCTOS(PRODUCT_ID),
    WAREHOUSE_ID INT FOREIGN KEY REFERENCES ALMACENES(WAREHOUSE_ID),
    STOCK INT NOT NULL
);

CREATE TABLE PEDIDOS (
    ORDER_ID INT PRIMARY KEY,
    BUYER_ID INT FOREIGN KEY REFERENCES USUARIOS(USER_ID),
    SELLER_ID INT FOREIGN KEY REFERENCES USUARIOS(USER_ID),
    PRODUCT_ID NVARCHAR(20) FOREIGN KEY REFERENCES PRODUCTOS(PRODUCT_ID),
    ORDER_DATE NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO),
    QUANTITY INT NOT NULL,
    PAYMENT_METHOD_ID INT FOREIGN KEY REFERENCES METODOS_PAGO(ID)
);

CREATE TABLE REVIEWS (
    REVIEW_ID NVARCHAR(12) PRIMARY KEY,
    PRODUCT_ID NVARCHAR(20) FOREIGN KEY REFERENCES PRODUCTOS(PRODUCT_ID),
    USER_ID INT FOREIGN KEY REFERENCES USUARIOS(USER_ID),
    RATING DECIMAL(3, 1) NOT NULL,
    CREATED_AT NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO)
);

CREATE TABLE MOTIVOS_DEVOLUCION (
    REASON_ID INT PRIMARY KEY,
    DESCRIPTION NVARCHAR(255) NOT NULL
);

CREATE TABLE DEVOLUCIONES (
    RETURN_ID INT PRIMARY KEY,
    ORDER_ID INT FOREIGN KEY REFERENCES PEDIDOS(ORDER_ID),
    RETURN_DATE NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO),
    WAREHOUSE_ID INT FOREIGN KEY REFERENCES ALMACENES(WAREHOUSE_ID),
    REASON_ID INT FOREIGN KEY REFERENCES MOTIVOS_DEVOLUCION(REASON_ID)
);