USE master;
GO

IF (EXISTS (SELECT name FROM master.sys.databases WHERE name = 'GeekMarket'))
BEGIN
    DROP DATABASE GeekMarket;
END;
GO

CREATE DATABASE GeekMarket;
GO

USE GeekMarket;
GO

CREATE TABLE FECHAS (
    PERIODO NVARCHAR(8) PRIMARY KEY,
    FECHA DATE NOT NULL,
    ANHO INT NOT NULL,
    MES INT NOT NULL,
    DIA INT NOT NULL,
    NOMBRE_MES NVARCHAR(20) NOT NULL,
    MES_CORTO NVARCHAR(10) NOT NULL,
    TRIMESTRE INT NOT NULL,
    NOMBRE_DIA NVARCHAR(20) NOT NULL
);

CREATE TABLE USUARIOS (
    USER_ID INT PRIMARY KEY,
    EMAIL NVARCHAR(255) NOT NULL,
    PASSWORD NVARCHAR(255) NOT NULL,
    USER_TYPE NVARCHAR(10) NOT NULL,
    CREATED_AT NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO)
);

CREATE TABLE PERSONAS_NATURALES (
    USER_ID INT PRIMARY KEY FOREIGN KEY REFERENCES USUARIOS(USER_ID),
    FIRST_NAME NVARCHAR(255) NOT NULL,
    LAST_NAME NVARCHAR(255) NOT NULL
);

CREATE TABLE EMPRESAS (
    USER_ID INT PRIMARY KEY FOREIGN KEY REFERENCES USUARIOS(USER_ID),
    RUC NVARCHAR(20) NOT NULL,
    BUSINESS_NAME NVARCHAR(255) NOT NULL
);

CREATE TABLE PAISES (
    COUNTRY_ID INT PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL
);

CREATE TABLE ALMACENES (
    WAREHOUSE_ID INT PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL,
    LOCATION NVARCHAR(255) NOT NULL,
    COUNTRY_ID INT FOREIGN KEY REFERENCES PAISES(COUNTRY_ID)
);

CREATE TABLE MARCAS (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCTOS (
    PRODUCT_ID INT PRIMARY KEY,
    USER_ID INT FOREIGN KEY REFERENCES USUARIOS(USER_ID),
    CATEGORY_ID INT FOREIGN KEY REFERENCES CATEGORIAS(CATEGORY_ID),
    BRAND_ID INT FOREIGN KEY REFERENCES MARCAS(ID),
    NAME NVARCHAR(255) NOT NULL,
    DESCRIPTION NVARCHAR(255) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    STOCK INT NOT NULL,
    WAREHOUSE_ID INT FOREIGN KEY REFERENCES ALMACENES(WAREHOUSE_ID),
    CREATED_AT NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO)
);

CREATE TABLE CATEGORIAS (
    CATEGORY_ID INT PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL,
    DESCRIPTION NVARCHAR(255) NOT NULL
);

CREATE TABLE PEDIDOS (
    ORDER_ID INT PRIMARY KEY,
    USER_ID INT FOREIGN KEY REFERENCES USUARIOS(USER_ID),
    PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCTOS(PRODUCT_ID),
    ORDER_DATE NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO),
    QUANTITY INT NOT NULL,
    TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL,
    PAYMENT_METHOD_ID INT FOREIGN KEY REFERENCES METODOS_PAGO(ID),
    STATUS NVARCHAR(20) NOT NULL
);

CREATE TABLE METODOS_PAGO (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255)
);

CREATE TABLE COMENTARIOS_Y_RESEÑAS (
    REVIEW_ID INT PRIMARY KEY,
    PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCTOS(PRODUCT_ID),
    USER_ID INT FOREIGN KEY REFERENCES USUARIOS(USER_ID),
    RATING INT NOT NULL,
    COMMENT NVARCHAR(255) NOT NULL,
    CREATED_AT NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO)
);

CREATE TABLE PAGOS (
    PAYMENT_ID INT PRIMARY KEY,
    ORDER_ID INT FOREIGN KEY REFERENCES PEDIDOS(ORDER_ID),
    AMOUNT DECIMAL(10, 2) NOT NULL,
    PAYMENT_DATE NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO)
);

CREATE TABLE MOTIVOS_DEVOLUCION (
    REASON_ID INT PRIMARY KEY,
    DESCRIPTION NVARCHAR(255) NOT NULL
);

CREATE TABLE DEVOLUCIONES (
    RETURN_ID INT PRIMARY KEY,
    ORDER_ID INT FOREIGN KEY REFERENCES PEDIDOS(ORDER_ID),
    RETURN_DATE NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO),
    WAREHOUSE_ID INT FOREIGN KEY REFERENCES ALMACENES(WAREHOUSE_ID),
    REASON_ID INT FOREIGN KEY REFERENCES MOTIVOS_DEVOLUCION(REASON_ID),
    STATUS NVARCHAR(20) NOT NULL
);

CREATE TABLE LOGISTICA (
    LOGISTICS_ID INT PRIMARY KEY,
    ORDER_ID INT FOREIGN KEY REFERENCES PEDIDOS(ORDER_ID),
    WAREHOUSE_ID INT FOREIGN KEY REFERENCES ALMACENES(WAREHOUSE_ID),
    SHIPPING_METHOD NVARCHAR(50),
    TRACKING_NUMBER NVARCHAR(50),
    SHIPPING_DATE NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO),
    DELIVERY_DATE NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO),
    STATUS NVARCHAR(20) NOT NULL
);

CREATE TABLE CAMPAÑAS_PUBLICITARIAS (
    CAMPAIGN_ID INT PRIMARY KEY,
    NAME NVARCHAR(255) NOT NULL,
    DESCRIPTION NVARCHAR(255) NOT NULL,
    START_DATE NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO),
    END_DATE NVARCHAR(8) NOT NULL FOREIGN KEY REFERENCES FECHAS(PERIODO),
    BUDGET DECIMAL(10, 2) NOT NULL
);
