CREATE TABLE USUARIOS (
    ID INT IDENTITY PRIMARY KEY,
    EMAIL NVARCHAR(255) NOT NULL UNIQUE,
    PASSWORD NVARCHAR(255) NOT NULL,
    NOMBRE_USUARIO NVARCHAR(50) NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    APELLIDO NVARCHAR(100) NOT NULL,
    DIRECCION NVARCHAR(255),
    TELEFONO NVARCHAR(20),
    FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    ROL NVARCHAR(50),
    ESTADO NVARCHAR(50)
);

CREATE TABLE PRODUCTOS (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    DESCRIPCION NVARCHAR(MAX),
    PRECIO DECIMAL(18, 2) NOT NULL,
    CANTIDAD INT NOT NULL,
    FECHA_PUBLICACION DATETIME DEFAULT GETDATE(),
    VENDEDOR_ID INT,
    CATEGORIA_ID INT,
    SUBCATEGORIA_ID INT,
    ESTADO NVARCHAR(50),
    URL_IMAGEN NVARCHAR(255),
    MARCA_ID INT,
    FOREIGN KEY (VENDEDOR_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID),
    FOREIGN KEY (SUBCATEGORIA_ID) REFERENCES SUBCATEGORIAS(ID),
    FOREIGN KEY (MARCA_ID) REFERENCES MARCAS(ID)
);

CREATE TABLE CATEGORIAS (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    DESCRIPCION NVARCHAR(MAX)
);

CREATE TABLE SUBCATEGORIAS (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    DESCRIPCION NVARCHAR(MAX),
    CATEGORIA_ID INT,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID)
);

CREATE TABLE MARCAS (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    DESCRIPCION NVARCHAR(MAX)
);

CREATE TABLE PROVEEDORES (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    CONTACTO NVARCHAR(255),
    DIRECCION NVARCHAR(255),
    TELEFONO NVARCHAR(20),
    EMAIL NVARCHAR(255)
);

CREATE TABLE PRODUCTOS_PROVEEDORES (
    ID INT IDENTITY PRIMARY KEY,
    PRODUCTO_ID INT,
    PROVEEDOR_ID INT,
    PRECIO_COMPRA DECIMAL(18, 2),
    FECHA_COMPRA DATETIME,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID),
    FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDORES(ID)
);

CREATE TABLE TRANSACCIONES (
    ID INT IDENTITY PRIMARY KEY,
    COMPRADOR_ID INT,
    VENDEDOR_ID INT,
    PRODUCTO_ID INT,
    FECHA INT,
    CANTIDAD INT NOT NULL,
    PRECIO_TOTAL DECIMAL(18, 2) NOT NULL,
    METODO_PAGO_ID INT,
    ESTADO NVARCHAR(50),
    FOREIGN KEY (COMPRADOR_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (VENDEDOR_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID),
    FOREIGN KEY (FECHA) REFERENCES TIME(ID),
    FOREIGN KEY (METODO_PAGO_ID) REFERENCES METODOS_PAGO(ID)
);

CREATE TABLE HISTORIAL_USUARIOS (
    ID INT IDENTITY PRIMARY KEY,
    USUARIO_ID INT,
    ACCION NVARCHAR(255),
    FECHA INT,
    DETALLES NVARCHAR(MAX),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (FECHA) REFERENCES TIME(ID)
);

CREATE TABLE DIRECCIONES (
    ID INT IDENTITY PRIMARY KEY,
    USUARIO_ID INT,
    DIRECCION NVARCHAR(255),
    CIUDAD NVARCHAR(100),
    ESTADO NVARCHAR(100),
    PAIS NVARCHAR(100),
    CODIGO_POSTAL NVARCHAR(20),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE VISITAS_PRODUCTOS (
    ID INT IDENTITY PRIMARY KEY,
    PRODUCTO_ID INT,
    USUARIO_ID INT,
    FECHA INT,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (FECHA) REFERENCES TIME(ID)
);

CREATE TABLE CARRITOS (
    ID INT IDENTITY PRIMARY KEY,
    USUARIO_ID INT,
    FECHA_CREACION INT,
    ESTADO NVARCHAR(50),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (FECHA_CREACION) REFERENCES TIME(ID)
);

CREATE TABLE CARRITO_PRODUCTOS (
    ID INT IDENTITY PRIMARY KEY,
    CARRITO_ID INT,
    PRODUCTO_ID INT,
    CANTIDAD INT NOT NULL,
    FOREIGN KEY (CARRITO_ID) REFERENCES CARRITOS(ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID)
);

CREATE TABLE METODOS_PAGO (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255),
    DESCRIPCION NVARCHAR(MAX)
);

CREATE TABLE INVENTARIOS (
    ID INT IDENTITY PRIMARY KEY,
    PRODUCTO_ID INT,
    CANTIDAD INT NOT NULL,
    ALMACEN_ID INT,
    FECHA_ULTIMA_ACTUALIZACION INT,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID),
    FOREIGN KEY (ALMACEN_ID) REFERENCES ALMACENES(ID),
    FOREIGN KEY (FECHA_ULTIMA_ACTUALIZACION) REFERENCES TIME(ID)
);

CREATE TABLE ALMACENES (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255),
    DIRECCION NVARCHAR(255),
    TELEFONO NVARCHAR(20),
    EMAIL NVARCHAR(255)
);

CREATE TABLE TIME (
    ID INT IDENTITY PRIMARY KEY,
    DATE DATE NOT NULL,
    YEAR INT NOT NULL,
    QUARTER INT NOT NULL,
    MONTH INT NOT NULL,
    MONTH_NAME NVARCHAR(50) NOT NULL,
    WEEK INT NOT NULL,
    DAY INT NOT NULL,
    DAY_NAME NVARCHAR(50) NOT NULL,
    IS_WEEKEND BIT NOT NULL
);

CREATE TABLE ENVIOS (
    ID INT IDENTITY PRIMARY KEY,
    TRANSACCION_ID INT,
    DIRECCION_ID INT,
    FECHA_ENVIO INT,
    FECHA_ENTREGA_ESTIMADA INT,
    FECHA_ENTREGA_REAL INT,
    ESTADO NVARCHAR(50),
    FOREIGN KEY (TRANSACCION_ID) REFERENCES TRANSACCIONES(ID),
    FOREIGN KEY (DIRECCION_ID) REFERENCES DIRECCIONES(ID),
    FOREIGN KEY (FECHA_ENVIO) REFERENCES TIME(ID),
    FOREIGN KEY (FECHA_ENTREGA_ESTIMADA) REFERENCES TIME(ID),
    FOREIGN KEY (FECHA_ENTREGA_REAL) REFERENCES TIME(ID)
);

CREATE TABLE DEVOLUCIONES (
    ID INT IDENTITY PRIMARY KEY,
    TRANSACCION_ID INT,
    FECHA_SOLICITUD INT,
    FECHA_PROCESO INT,
    ESTADO NVARCHAR(50),
    RAZON NVARCHAR(MAX),
    FOREIGN KEY (TRANSACCION_ID) REFERENCES TRANSACCIONES(ID),
    FOREIGN KEY (FECHA_SOLICITUD) REFERENCES TIME(ID),
    FOREIGN KEY (FECHA_PROCESO) REFERENCES TIME(ID)
);
