USE master;
GO

IF (EXISTS (SELECT name FROM master.sys.databases WHERE name = 'GeekMarket'))
BEGIN
    DROP DATABASE GeekMarket;
END;
GO

CREATE DATABASE GeekMarket;
GO

USE GeekMarket;
GO

CREATE TABLE GEOGRAFIA (
    ID INT IDENTITY PRIMARY KEY,
    PAIS NVARCHAR(255) NOT NULL,
    CIUDAD NVARCHAR(255) NOT NULL
);

CREATE TABLE USUARIOS (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    APELLIDO NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL UNIQUE,
    TELEFONO NVARCHAR(20),
    FECHA_REGISTRO DATETIME,
    GEOGRAFIA_ID INT,
    FOREIGN KEY (GEOGRAFIA_ID) REFERENCES GEOGRAFIA(ID)
);

CREATE TABLE TIENDAS (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE_EMPRESA NVARCHAR(255) NOT NULL,
    RUC NVARCHAR(20) NOT NULL UNIQUE,
    TELEFONO NVARCHAR(20),
    EMAIL NVARCHAR(255) NOT NULL UNIQUE,
    FECHA_REGISTRO DATETIME,
    GEOGRAFIA_ID INT,
    FOREIGN KEY (GEOGRAFIA_ID) REFERENCES GEOGRAFIA(ID)
);

CREATE TABLE CATEGORIAS (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    DESCRIPCION NVARCHAR(255)
);

CREATE TABLE SUBCATEGORIAS (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    DESCRIPCION NVARCHAR(255),
    CATEGORIA_ID INT,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID)
);

CREATE TABLE MARCAS (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCTOS (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255) NOT NULL,
    PRECIO DECIMAL(18, 2) NOT NULL,
    VENDEDOR_ID INT,
    CATEGORIA_ID INT,
    SUBCATEGORIA_ID INT,
    MARCA_ID INT,
    FOREIGN KEY (VENDEDOR_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID),
    FOREIGN KEY (SUBCATEGORIA_ID) REFERENCES SUBCATEGORIAS(ID),
    FOREIGN KEY (MARCA_ID) REFERENCES MARCAS(ID)
);

CREATE TABLE METODOS_PAGO (
    ID INT IDENTITY PRIMARY KEY,
    NOMBRE NVARCHAR(255)
);

CREATE TABLE FECHAS (
    PERIODO NVARCHAR(8) PRIMARY KEY,
    FECHA DATE NOT NULL,
    ANHO INT NOT NULL,
    MES INT NOT NULL,
    DIA INT NOT NULL,
    NOMBRE_MES NVARCHAR(20) NOT NULL,
    MES_CORTO NVARCHAR(10) NOT NULL,
    TRIMESTRE INT NOT NULL,
    NOMBRE_DIA NVARCHAR(20) NOT NULL
);

CREATE TABLE TRANSACCIONES_USUARIOS (
    ID INT IDENTITY PRIMARY KEY,
    COMPRADOR_ID INT,
    VENDEDOR_ID INT,
    PRODUCTO_ID INT,
    PERIODO NVARCHAR(8),
    CANTIDAD INT NOT NULL,
    PRECIO_TOTAL DECIMAL(18, 2) NOT NULL,
    METODO_PAGO_ID INT,
    ESTADO NVARCHAR(50),
    FOREIGN KEY (COMPRADOR_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (VENDEDOR_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID),
    FOREIGN KEY (PERIODO) REFERENCES FECHAS(PERIODO),
    FOREIGN KEY (METODO_PAGO_ID) REFERENCES METODOS_PAGO(ID)
);
