USE master;
go

IF( EXISTS ( SELECT name FROM master.sys.databases WHERE name = 'STAGE_BANK' ) )
BEGIN
	DROP DATABASE STAGE_BANK;
END;
go

CREATE DATABASE STAGE_BANK;
go

USE STAGE_BANK;
go


CREATE TABLE DIM_TIPOMOVIMIENTO (
    PK_TIPOMOVIMIENTO INT IDENTITY NOT NULL,
    NOMBRE_MOVIMIENTO VARCHAR(30),
    ESTADO CHAR(1),
    CODIGO_MOVIMIENTO VARCHAR(10),
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
);

SELECT*FROM DIM_TIPOMOVIMIENTO

CREATE TABLE DIM_SUCURSAL (
    PK_SUCURSAL INT IDENTITY NOT NULL,
    NOMBRE_SUCURSAL VARCHAR(50),
    CIUDAD VARCHAR(30),
    COD_SUCURSAL VARCHAR(10),
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
);

SELECT*FROM DIM_SUCURSAL

CREATE TABLE DIM_EMPLEADO (
    PK_EMPLEADO INT IDENTITY NOT NULL,
    NOMBRE_COMPLETO VARCHAR(100),
    TIPO_DOCUMENTO VARCHAR(10),
	DNI_EMPLEADO VARCHAR(10),
	TURNO_ASIGNADO	VARCHAR(10),
	COD_EMPLEADO VARCHAR(10),
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
);

SELECT*FROM DIM_EMPLEADO

CREATE TABLE DIM_CLIENTE (
    PK_CLIENTE INT IDENTITY NOT NULL,
    COD_CLIENTE VARCHAR(10),
    NOMBRE_COMPLETO VARCHAR(100),
    TIPO_CLIENTE VARCHAR(10),
    NUM_DOCU VARCHAR(10),
    CIUDAD VARCHAR(30),
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
);

SELECT*FROM DIM_CLIENTE


--------------------------------------------------------------------

CREATE TABLE FACT_MOVIMIENTO (
    PK_MOVIMIENTO INT IDENTITY NOT NULL,
    PK_CLIENTE INT,
	PK_SUCURSAL INT,
	PK_TIPOMOVIMIENTO INT,
	PK_EMPLEADO INT,
	MONEDA VARCHAR(10),
	IMPORTE FLOAT,
	INTERES FLOAT,
	SALDO FLOAT,
	COD_MOVIMIENTO VARCHAR(10),
    FEC_CREACION DATE,
    USU_CREACION VARCHAR(50)
);

select*from FACT_MOVIMIENTO
