USE master;
go

IF( EXISTS ( SELECT name FROM master.sys.databases WHERE name = 'GREENBANK_SOLIMOV' ) )
BEGIN
	DROP DATABASE GREENBANK_SOLIMOV;
END;
go

CREATE DATABASE GREENBANK_SOLIMOV;
go

USE GREENBANK_SOLIMOV;
go

CREATE TABLE USUARIOS (
    ID INT PRIMARY KEY,
    EMAIL NVARCHAR(255) NOT NULL,
    PASSWORD NVARCHAR(255) NOT NULL,
    APELLIDOS NVARCHAR(255),
    NOMBRES NVARCHAR(255),
    REGISTRO DATETIME,
    AREA NVARCHAR(255),
    ROLES NVARCHAR(255),
    ACTIVO BIT,
    APROBADOR_ID INT,
    APROBADOR_BACKUP_ID INT
);

CREATE TABLE SOLICITUDES (
    ID INT PRIMARY KEY,
    TIPO NVARCHAR(255),
    ESTADO NVARCHAR(255),
    MONTO_TOTAL_SOLES DECIMAL(18, 2),
    MONTO_TOTAL_DOLARES DECIMAL(18, 2),
    USUARIO_ID INT,
    FECHA_CREACION DATETIME,
    FECHA_ACTUALIZACION DATETIME,
    APROBADOR_ID INT,
    APROBADOR_BACKUP_ID INT,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (APROBADOR_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (APROBADOR_BACKUP_ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE ABONOS (
    ID INT PRIMARY KEY,
    CONCEPTO NVARCHAR(255),
    CUENTA NVARCHAR(255),
    CUENTA_CONTABLE NVARCHAR(255),
    MONEDA NVARCHAR(255),
    MONTO DECIMAL(18, 2),
    NOTA NVARCHAR(255),
    EMISORA NVARCHAR(255),
    RECEPTORA NVARCHAR(255),
    GLOSA NVARCHAR(255),
    TARJETA NVARCHAR(255),
    ID_OPERACION INT,
    SOLICITUD_ID INT,
    FOREIGN KEY (SOLICITUD_ID) REFERENCES SOLICITUDES(ID)
);

CREATE TABLE ANULACIONES_OP (
    ID INT PRIMARY KEY,
    CONCEPTO NVARCHAR(255),
    CUENTA NVARCHAR(255),
    CUENTA_CONTABLE NVARCHAR(255),
    MONEDA NVARCHAR(255),
    MONTO DECIMAL(18, 2),
    NOTA NVARCHAR(255),
    EMISORA NVARCHAR(255),
    RECEPTORA NVARCHAR(255),
    NUMER_OP NVARCHAR(255),
    ID_OPERACION INT,
    SOLICITUD_ID INT,
    FOREIGN KEY (SOLICITUD_ID) REFERENCES SOLICITUDES(ID)
);

CREATE TABLE CARGOS (
    ID INT PRIMARY KEY,
    CONCEPTO NVARCHAR(255),
    CUENTA NVARCHAR(255),
    CUENTA_CONTABLE NVARCHAR(255),
    MONEDA NVARCHAR(255),
    MONTO DECIMAL(18, 2),
    NOTA NVARCHAR(255),
    EMISORA NVARCHAR(255),
    RECEPTORA NVARCHAR(255),
    GLOSA NVARCHAR(255),
    ID_OPERACION INT,
    SOLICITUD_ID INT,
    FOREIGN KEY (SOLICITUD_ID) REFERENCES SOLICITUDES(ID)
);

CREATE TABLE EMISIONES_OP (
    ID INT PRIMARY KEY,
    CONCEPTO NVARCHAR(255),
    CUENTA NVARCHAR(255),
    CUENTA_CONTABLE NVARCHAR(255),
    MONEDA NVARCHAR(255),
    MONTO DECIMAL(18, 2),
    NOTA NVARCHAR(255),
    EMISORA NVARCHAR(255),
    RECEPTORA NVARCHAR(255),
    DNI NVARCHAR(255),
    ID_OPERACION INT,
    SOLICITUD_ID INT,
    FOREIGN KEY (SOLICITUD_ID) REFERENCES SOLICITUDES(ID)
);

CREATE TABLE OPERACIONES_CAMBIO (
    ID INT PRIMARY KEY,
    CONCEPTO NVARCHAR(255),
    CUENTA_CONTABLE_1 NVARCHAR(255),
    CUENTA_CONTABLE_2 NVARCHAR(255),
    MONEDA NVARCHAR(255),
    MONTO DECIMAL(18, 2),
    NOTA_1 NVARCHAR(255),
    EMISORA_1 NVARCHAR(255),
    RECEPTORA_1 NVARCHAR(255),
    NOTA_2 NVARCHAR(255),
    EMISORA_2 NVARCHAR(255),
    RECEPTORA_2 NVARCHAR(255),
    TIPO NVARCHAR(255),
    EQUIVALENTE DECIMAL(18, 2),
    ID_OPERACION INT,
    SOLICITUD_ID INT,
    TICKET_TIPO_CAMBIO NVARCHAR(255),
    FOREIGN KEY (SOLICITUD_ID) REFERENCES SOLICITUDES(ID)
);

CREATE TABLE PAGOS_TC (
    ID INT PRIMARY KEY,
    CONCEPTO NVARCHAR(255),
    CUENTA_CONTABLE NVARCHAR(255),
    MONEDA NVARCHAR(255),
    MONTO DECIMAL(18, 2),
    NOTA NVARCHAR(255),
    EMISORA NVARCHAR(255),
    RECEPTORA NVARCHAR(255),
    TARJETA NVARCHAR(255),
    ID_OPERACION INT,
    SOLICITUD_ID INT,
    FOREIGN KEY (SOLICITUD_ID) REFERENCES SOLICITUDES(ID)
);

CREATE TABLE TRANSFERENCIAS_EC (
    ID INT PRIMARY KEY,
    CONCEPTO NVARCHAR(255),
    MONEDA NVARCHAR(255),
    MONTO DECIMAL(18, 2),
    ID_OPERACION INT,
    SOLICITUD_ID INT,
    CUENTA_CARGO NVARCHAR(255),
    CUENTA_ABONO NVARCHAR(255),
    FOREIGN KEY (SOLICITUD_ID) REFERENCES SOLICITUDES(ID)
);

CREATE TABLE HISTORIAL_SOLICITUDES (
    ID INT PRIMARY KEY,
    ESTADO_ANTERIOR NVARCHAR(255),
    ESTADO_NUEVO NVARCHAR(255),
    FECHA_CAMBIO DATETIME,
    USUARIO_ID INT,
    SOLICITUD_ID INT,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID),
    FOREIGN KEY (SOLICITUD_ID) REFERENCES SOLICITUDES(ID)
);
